### ISSUE TITLE
Latest version of byteman fails with @Rule

### ISSUE THREAD

**Issue by edwardoliveira** [reta/spring-jpa-byteman#1]
Hi,

First and foremost, *thanks for this code and blog post*! :) :+1: 

Well, after upgrading for latest version of Byteman (3.0.2) the tests fail with the following message:

```
load script file requested with no current configuration <class name>
```

Any idea of how solving that?

Thanks in advance!

**Comment by reta** [comment]
Hi Edward!

Thank you, much appreciated, glad you found it helpful! You are very right indeed, the examples do not run with latest Byteman 3.0.2. I updated the project, please pull the latest master, everything should be working fine now :-) Please let me know if you are still having some issues!

Thanks!

Best Regards,
    Andriy Redko

**Comment by edwardoliveira** [comment]
Thank you **very much**, Andriy! :grinning: 

It worked with new version of the Byteman. Closing this issue then. 

Thanks again!

Best regards,
Edward
